### ISSUE TITLE
Missing Assignment for Section 12

### ISSUE THREAD

**Issue by RaimiSol** [PacktPublishing/Angular---The-Complete-Guide---2023-Edition#1]
I'm following the course on the O'Reilly learning platform. In section 2 the instructor gives an assignment in section 12. The previous sections had a project code zip folder for the assignments start and solution. But in section 12 there is only the [project code zip folder final](https://github.com/PacktPublishing/Angular---The-Complete-Guide---2023-Edition/blob/a1e28f3d4e421319df5df998a50157615fbdc82f/Section%2012%20-%20Course%20Project%20-%20Routing/prj-routing-final.zip) which already contains the implemented solution.

It would be nice to add the assignment start and solution folders for the section 12.

**Comment by Sonakshis** [comment]
Hi 
Section 12 does not have any assignments. The author proceeds to incorporate routing into the project. The code for the project for section 12 is present here: https://github.com/PacktPublishing/Angular---The-Complete-Guide---2023-Edition/tree/c357dcb77d2dcf0f9c32864254b9f81a6f81afef/Section%2012%20-%20Course%20Project%20-%20Routing
